### PR TITLE
seperated qrcode code into a seperate repo

### PR DESCRIPTION
**Pull request by rubensayshi**
I seperated the code that was in `lib` into a seperate repo/package: https://github.com/blocktrail/qrcode-canvas

this way it's possible to install that dependancy in projects that just want to browserify it and it's possible without needing to install all the `node-canvas` stuff.

idk if you're interested in this seperation (and if you are ofc it needs a little bit more documentation and work (and it should be you who manages the seperated code).  
if not then just close the PR, I felt I should let you know at the very least when I fork your project ...

### CODE REVIEW

**Comment by soldair** [comment]
i like this idea. canvas has always been a problem

**Comment by soldair** [comment]
i am too sleepy right now to make long term decisions but ill figure this out. i can probably add you as a collaborator here and you likewise under the amazing open open source project terms https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md

**Comment by rubensayshi** [comment]
well it does not get rid of the depedancy for `node-canvas` when using NodeJS, but your code seems to be the cleanest of the various qrcode implementations I've came across so I'd like to use it in my browserified module :)

**Comment by soldair** [comment]
thanks for the pr. I'm happy you used this to make other modules. Because this pr moves all of the code bit for bit to another project I don't think its helpful for this module.

i wish you much luck. thanks for the advice

**Pull request closed without merging**
