### PR TITLE
Refactor/core

### PR DESCRIPTION
**Pull request by vigreco**
This is the first part of the refactor proposed in #56.
It is focused on lib structure and reorganization of core files.

The initial qrcode.js file has been splitted in many separated modules to make code easier to follow and update.
Some parts have been reimplemented and where possible some optimisations have been added to make the qrcode generation faster.
Also, I tried to comment and document as much as possible the code to explain what it does.

For each core module has been added an initial test file which cover the implementation.
More tests should be added in future to cover possible edge cases.

Example files have been moved to a dedicated folder and all files not needed have been excluded from publishing to have a cleaner package.

### CODE REVIEW

**Comment by soldair** [comment]
wow! ill take a look now

**Comment by soldair** [comment]
one issue is that prepublish runs on npm install also. this means that folks have to run the tests just to install it as a dep

**Comment by vigreco** [comment]
It makes sense. I'll remove the test task from prepublish.

**Comment by vigreco** [comment]
I've just noticed there was a bug in encode method that would occur using numeric or alphanumeric mode. Probably also in some rare cases in byte mode. Fixed now.

(num and alphanum modes are not implemented yet, I'm working on them in another branch, I hope to push it soon)

**Comment by soldair** [comment]
this is amazing work. i just wanted to say thanks! and im glad you are digging in

**Comment by vigreco** [comment]
it's a pleasure 😄 
Let me know if there is something else you want me to change 👍

**Comment by soldair** [comment]
if you think this is ready to god i approve. please go ahead and merge.

**Comment by vigreco** [comment]
@soldair I added a few changes. If it's still ok for you I'm ready to merge this.

**Comment by soldair** [comment]
hmm. if anyone is using the `build` path in their scripts that require this libraray their scripts will be broken.
we'll have to release this in a semver major change. with all of these changes we may already have to.
did we change the api/arguments in any other non backwards compatible way?

**Comment by vigreco** [comment]
mm ok, you've right, I hadn't thought of that. I probably have to revert it to the old name for now.

I've intentionally kept all the API untouched for this first part of the refactor.
All the changes affect only the internal code.
I'll introduce some changes and some new API in the refactor of the rendering part, I think.
Anyway should not be a problem keep also the current interface for backward compatibility.
 
The only thing that I've removed is one of the global var exported for the browser.
Now there's only `window.qrcodelib` (window.QRCodeLib has been removed) since the readme was covering only the former, [here](https://github.com/soldair/node-qrcode/tree/master#client-side-api).

A rough roadmap for the next changes could be:
- 0.6.0: core refactor
- 0.7.0: add support for Numeric and Alphanumeric mode (with auto select of best mode)
- 0.8.0: renderer refactor
- 0.9.0: add support for other output formats (jpg, pdf, css, table, ascii, ...)
- 1.0.0: initial support for image effects (logo, shadow, rounded modules, ...)

**Comment by soldair** [comment]
awesome :+1:

**Comment by soldair** [comment]
:sheep:

**Comment by soldair** [comment]
:clap: :confetti_ball:

**Pull request merged**
