### PR TITLE
adding toString svg output to browser version

### PR DESCRIPTION
**Pull request by soldair**
fixes https://github.com/soldair/node-qrcode/issues/75 ish

### CODE REVIEW

**Comment by vigreco** [comment]
@soldair this will works just fine using the precompiled bundle but I think that the `renderToFile` function in `svg.js` may create some problem if someone use this lib with webpack for example.
It also problably won't work in a react-native app for the same reason.

We should move the code which depends on `require('fs')` somewhere else.

**Comment by vigreco** [comment]
@soldair, I was thinking that adding `"fs": false` in package.json should workaround the problem, at least for bundlers that support it.

```json
...
"browser": {
    "./lib/index.js": "./lib/browser.js",
    "./lib/utils/buffer.js": "./lib/utils/typedarray-buffer.js",
    "fs": false
  }
...
```

**Comment by soldair** [comment]
oh great idea. yeah i should have pulled that into the method.
im not sure why the lint failures in 4.2.1 though

**Comment by vigreco** [comment]
I guess it's due to [this](https://github.com/soldair/node-qrcode/blob/master/package.json#L51).
Seems that the last version of standard have new rules.
We can specify the previous version in place of `*` to quick solve this: `^9.0.2`

**Pull request merged**
