### PR TITLE
Update node-canvas version

### PR DESCRIPTION
**Pull request by throrin19**
Update node-canvas version to `1.2.9` to get the compatibility with NodeJS 4.0.0

### CODE REVIEW

**Comment by soldair** [comment]
thanks! ill try it manually because travis is bombing on some deps

**Comment by soldair** [comment]
I'm adding you as a contributor because this is an open opensource project. thanks for the help!!
please review the guidelines in CONTRIBUTING.md

**Comment by throrin19** [comment]
Thanks

**Comment by soldair** [comment]
published 0.4.0

**Comment by throrin19** [comment]
Great :+1:  Thanks

**Pull request merged**
