### PR TITLE
Add BufferCanvas to remove node-canvas

### PR DESCRIPTION
**Pull request by ryohey**
Hello there
I used this module to my project and works perfectly for Mac.
but Its too hard to run on Windows. Someone noticed too.

> Because of the deep dependency, qrcode is too hard to use.
> qrcode's dependency: qrcode -> node-canvas -> node -> Cairo -> x11.

https://github.com/imsobear/node-qrcode

I wrote the code Canvas alternative class to remove node-canvas and it's working.
BufferCanvas implements few interfaces from Canvas API used in node-qrcode.
It provides a pure JS way to render rectangles.
What do you think about this?

### CODE REVIEW

**Comment by soldair** [comment]
looks pretty good. im all for getting rid of the native dep. its been a thorn in my side for 5 years or so
canvas is not included in the browser bundle neither are any of the renderers so the es6 shouldnt be a problem. curious if @vigreco has an opinion about how best to integrate this. it would have to be a major bump in any case.

**Comment by vigreco** [comment]
Actually ES6 may be a problem here since it's available only by node.js v4 and above. We are now supporting node ver >= 0.10
Also, `pngjs` in version 3.0.0 has dropped support for node below v4 and we should stick with version 2.3.0 if we want to keep compatibility with node v0.10 and v0.12.
We should probably consider to stop supporting very old versions of node too.

Apart from that, I think this is a good starting point to move towards the rendering refactor.
I would as next step get rid of canvas related stuff and move as much possible "rendering logic" from `lib/index.js` into renderers.

`buffer-canvas.js` could then be renamed just as `renderer/png.js` and we could adapt the current `renderer/qrcode-draw.js` in `renderer/canvas.js` which will handle the browser canvas and keep support for `node-canvas` (for whom wants to use it) without depend from it.

**Comment by yomansk8** [comment]
Hello !
I'm wondering if this will be merged soon or not ?
We're actually trying to use node-qrcode inside of an alpine linux docker image and the deep dependancies of canvas are really annoying us...

Anyway, thanks for the good work ;)

**Comment by soldair** [comment]
we were blocked on merging this because of the es6
we would love it if someone took it over the finish line reafcotred it to es5 and i so no reason we couldnt move forward.

**Comment by yomansk8** [comment]
I see. I think that i'm gonna have a look at this ;)
If I have something that sounds good to me, I will come to you with a pull request ;)

**Comment by ryohey** [comment]
Sorry for such late reply.
Then thankfully I fixed ES6 problem by referring to the code of yomansk8.

**Comment by eseliger** [comment]
@soldair This would really help with setting up environments, can this be merged somewhen soon? 🙈

**Comment by soldair** [comment]
canvas has been removed as of 0.8.0which is the new latest on npm. 
thank you everyone for your contributions.

please file issues or make more prs for any issue you've found.

**Pull request closed without merging**
