### PR TITLE
Avoid dependency on Buffer

### PR DESCRIPTION
**Pull request by LinusU**
This patch replaces the usage of `Buffer` with plain `Uint8Array`s.

Technically, this is a breaking change for browsers that don't support `Uint8Array`, but the support have been there for a long time:

Screenshot 2020-03-30 at 18 22 19

Personally, I would recommend anyone wanting to support IE 9 to use a polyfill, instead of us including workarounds in this package. But I'm happy to hear other opinions ☺️

### CODE REVIEW

**Comment by LinusU** [comment]
(the test is failing because encode-utf8 is using `let`/`const`, force pushing fix now 😬)

**Comment by LinusU** [comment]
Upgraded Standard to v14 and fixed the lining issues.

The build is failing on Node v12 because Canvas 1.x doesn't work on that version...

**Comment by LinusU** [comment]
One approach would be to cut a new major release, bump the minimum required Node.js, and upgrade to Canvas v2.x. Would be happy to do the job if you want to go that route 💪

**Comment by soldair** [comment]
I approve of this.
I'm ok with dropping testing on nodejs < 10 and releasing a major

**Comment by LinusU** [comment]
Awesome, I'll add a commit to bump minimum supported Node.js & update the test matrix 💪

**Comment by LinusU** [comment]
Okay, I've done quite a few things now:

- Set the minimum supported version to Node.js 10.13.0
  - This is the first version of Node.js 10 that was considered LTS
  - and also the minimum supported version for `pngjs` 5.x
  - Travis is now setup to test on this exact version, and latest stable versions (10.x, 12.x)
- Updated all dependencies to latest greatest! 💅 
- Removed dependencies that is now supported natively (e.g. `os-tempdir`, and also used `mkdir` with `{ recursive: true }` to avoid checking if there is a directory first)
- Upgraded the build script to work with UglifyJS 3 and to simplify it using modern Node.js functions
- Changed all `var` to `let` or `const`
  - This was done as a separate commit if you don't want it ☺️ 
  - It was done by changing all `var` to `let`, and then running `standard --fix`
  - There was a few for-loops that were reusing each others `i` or `n`, that was fixed to add `let` to both, StandardJS helpfully complained about those 💅 
- Added myself to the list of contributors in the package.json ☺️ 

-----

Ah, crappers, UglifyJS doesn't like `const`/`let` 😅

Okey, this kind of ties in to another thing I was going to ask anyways:

What browsers do you want to support with the prebuilt files? pngjs is now using `const`/`let` as well so unless we want to stay on the old version we will have `const`/`let` in the code.

If you want to, I'd be happy to setup Babel for the browser build with preset-env. That way we can specify exactly which browsers to support, and we can document that support clearly in the Readme.

We can then use babel to do the minification as well, so that we can just trade one tool for another (e.g. remove UglifyJS, add Babel) instead of just adding ☺️ (also, `tap` already depends on Babel so it's installed anyways 😅)

Let me know how you want to proceed 👍

**Comment by soldair** [comment]
We have a few users opening issues about browser compatibility. I suggest that they bundle themselves, but if we have an easy way to generate bundles for specific feature years that sounds cool. Not sure what the baseline should be but happy to let you choose one.

**Comment by LinusU** [comment]
> I suggest that they bundle themselves

Yeah I agree totally 👍 

I guess that this is just for people that aren't using Npm and are just dropping the bundle straight to their website...

> Not sure what the baseline should be but happy to let you choose one.

We aren't really using any new features so I'm open to keeping this wide. I will do some quick comparisons on the output bundle size and make a decision ☺️ 

-----

While we're doing breaking changes 😅, what do you think about dropping callbacks entirely in favour of `Promise`s? I guess that this is quite subjective, so it's totally up to you

**Comment by LinusU** [comment]
Previous bundle size (minified + gzipped): 9.7k
New bundle size (minified + gzipped): 8.9k

I think that switching from Browserify to rollup did the largest change ☺️ 

There was no difference in bundle size with different browser support so opted for IE 10+, Safari 5.1+ per the table in my first post.

-----

I'm still in favour of dropping the bundles completely if you rather do that 👍

**Comment by LinusU** [comment]
Thanks for merging 🚀

**Comment by soldair** [comment]
No problem. Thanks so much for your work on this!  I'll try and get a release published soon

**Pull request merged**
