### PR TITLE
API/renderer refactor

### PR DESCRIPTION
**Pull request by vigreco**
These are some changes I'm working on recently which include the refactor of renderer functions and public apis.

Summary of changes so far:

### New api
I tried to change the api to be more generic and that works across different renderer. New methods are:
- `toCanvas()`
- `toString()`
- `toDataURL()`
- `toFile()`
- `toFileStream()`

The output format can be choosen by 'type' option. Es:
```javascript
// If type is not specified, the format will be guessed from file extension
// Supported types so far are: png, svg, txt (utf8 also works)
QRCode.toFile('filename', 'Text to encode', { type: 'png' }, function (err) {
  ...
})
```
```javascript
QRCode.toDataURL('filename', 'Text to encode', { type: 'image/png' }, function (err, url) {
  ...
})
```
```javascript
// Other options can be used as always
QRCode.toString('filename', 'Text to encode', { 
  type: 'svg',
  version: 2,
  errorCorrectionLevel: 'L'
}, function (err, xml) {
  ...
})
```

### Remove node-canvas dependency
This has been requested for a while now. The new canvas renderer will work for both browser and node canvas without requiring any mandatory dependency.
`node-canvas` user will have to pass an additional parameter with the canvas object.
```javascript
// In node you have to pass a canvas instance
var canvas = new Canvas(200, 200)
QRCode.toCanvas(canvas, 'Some text', { errorCorrectionLevel: 'H' }, function (err, canvas) {
  ...
})

// In browser if first parameter is omitted, a new canvas element will be created
QRCode.toCanvas('Some text', { errorCorrectionLevel: 'H' }, function (err, canvasElement) {
  ...
})
```

### Renderers
- Render to canvas in browser has been improved using an ImageData in place of multiple calls to `drawRect`. This has reduced rendering time by half.
- Svg renderer has been updated to support transparent colors.
- A png renderer has been added to replace the previous implementation based on `node-canvas`.
- An utf8 renderer has been added to support drawing qr to terminal. Can also be used through toString() function.

### TO DO
- [x] Fix tests errors
- [x] 100% code coverage
- [x] Use Async I/O functions
- [x] Update readme
- [x] Support legacy API
- [x] Update other examples

Please let me know your thoughts 😄

### CODE REVIEW

**Comment by soldair** [comment]
have to review more but :heart: 
what do we need for legacy api compatabillity?

**Comment by vigreco** [comment]
To support old APIs I was thinking that something simple like wrapping the new functions should work. Es:

node:
```javascript
exports.drawSvg = function (text, opts, cb) {
  if (!opts) opts = {}
  // force svg output
  opts.type = 'svg'
  return exports.toString(text, opts, cb)
}

// These behave the same way if option.type is not specified. We can just use an alias
exports.save = exports.toFile
exports.drawPNGStream = exports.toFileStream
```

browser:
```javascript
exports.qrcodedraw = function () {
// code to handle options here
...

return {
  draw: exports.toCanvas
}
```

I've not tryed this code yet, I guess it should work unless I've missed something.

**Comment by soldair** [comment]
:clap:

**Comment by vigreco** [comment]
I made another couple of changes, I think it's ok now.

I removed constraints for margin values as introduced in [f4ee7e](https://github.com/soldair/node-qrcode/commit/f4ee7e59edad10ef2415b6519449242488acbc4f) and fixed an error which occurs in html pages that haven't utf8 as charset.

**Comment by soldair** [comment]
this is amazing work. and absolutely should be published as a new minor? release. i think things are backwards compatable but it is big so minor feels good to me. @vigreco would you like to publish or shall i?

thank you thank you thank you for this. folks are really going to appreciate this work.

**Comment by soldair** [comment]
got impatient =) 0.8.0

**Comment by vigreco** [comment]
Thank you for publishing this @soldair! So sorry for the delay, I've been out for all day.
(I had a chance to work on a couple of thing though, I'll send a PR soon)

**Pull request merged**
