### PR TITLE
Passing options down to drawSvg in QRCode.save

### PR DESCRIPTION
**Pull request by lixiaoyan**

### CODE REVIEW

**Comment by soldair** [comment]
oh this looks great. thank you!

**Comment by vigreco** [comment]
@soldair, should we allow to completely remove margins?

A border of minimum 4 modules is required by qr code specs and it's part of the symbol.
A qr code without that margin isn't considered valid even though could be still readable.

Also, since is requested by specs, qr code readers expect such a margin when scanning a symbol.

**Comment by lixiaoyan** [comment]
We can add spacing by other way (e.g. using padding in css) instead of
includes it in image. It give us more customization for rendering a qrcode.

**Comment by vigreco** [comment]
Of course, I see your point, but that space around the qr is actually part of the symbol such as the black dots inside.
If you remove the border, you have an invalid symbol as much as if you remove an alignment square, even though you can still read the qr in both cases.

You could add back the margin with css or something else, but the point is that the lib has just generated an invalid symbol.
We should always produce a valid symbol that follows the specs and configurations should not break this thing.

That said, I'm aware that the current implementation allows users to set a margin less than 4 which is also wrong based on what I've just stated. I'm working on a refactor of the renderer part which will handle this case too.

**Pull request merged**
